config/routes.rb
Rails.application.routes.draw do
  resources :mainpages
  resources :quotes
  resources :jokes

   root 'mainpages#index'

 

end

app/models/joke.rb
class Joke < ActiveRecord::Base
end

app/models/mainpage.rb
class Mainpage < ActiveRecord::Base
end

app/models/quote.rb
class Quote < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def show
   @joke = Joke.offset(rand(Joke.count)).first
   @quote = Quote.offset(rand(Quote.count)).first
  end

end

app/controllers/jokes_controller.rb
class JokesController < ApplicationController
  before_action :set_joke, only: [:show, :edit, :update, :destroy]

  # GET /jokes
  # GET /jokes.json
  def index
    #@jokes = Joke.all
    @joke = Joke.offset(rand(Joke.count)).first
  end

  # GET /jokes/1
  # GET /jokes/1.json
  def show
   @joke = Joke.offset(rand(Joke.count)).first
  end
  def random
  @random = Joke.first
  end

  # GET /jokes/new
  def new
    @joke = Joke.new
  end

  # GET /jokes/1/edit
  def edit
  end

  # POST /jokes
  # POST /jokes.json
  def create
    @joke = Joke.new(joke_params)

    respond_to do |format|
      if @joke.save
        format.html { redirect_to @joke, notice: 'Joke was successfully created.' }
        format.json { render :show, status: :created, location: @joke }
      else
        format.html { render :new }
        format.json { render json: @joke.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jokes/1
  # PATCH/PUT /jokes/1.json
  def update
    respond_to do |format|
      if @joke.update(joke_params)
        format.html { redirect_to @joke, notice: 'Joke was successfully updated.' }
        format.json { render :show, status: :ok, location: @joke }
      else
        format.html { render :edit }
        format.json { render json: @joke.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jokes/1
  # DELETE /jokes/1.json
  def destroy
    @joke.destroy
    respond_to do |format|
      format.html { redirect_to jokes_url, notice: 'Joke was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_joke
      @joke = Joke.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def joke_params
      params.require(:joke).permit(:joke, :punchline)
    end
end

app/controllers/mainpages_controller.rb
class MainpagesController < ApplicationController
  before_action :set_mainpage, only: [:show, :edit, :update, :destroy]

  # GET /mainpages
  # GET /mainpages.json
  def index
    @jokes = Joke.offset(rand(Joke.count)).first
    @random_joke = Joke.all.shuffle
    @random_quote = Quote.all.shuffle
    @quotes = Quote.offset(rand(Quote.count)).first
  end

  # GET /mainpages/1
  # GET /mainpages/1.json
  def show
  end

  # GET /mainpages/new
  def new
    @mainpage = Mainpage.new
  end

  # GET /mainpages/1/edit
  def edit
  end

  # POST /mainpages
  # POST /mainpages.json
  def create
    @mainpage = Mainpage.new(mainpage_params)

    respond_to do |format|
      if @mainpage.save
        format.html { redirect_to @mainpage, notice: 'Mainpage was successfully created.' }
        format.json { render :show, status: :created, location: @mainpage }
      else
        format.html { render :new }
        format.json { render json: @mainpage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mainpages/1
  # PATCH/PUT /mainpages/1.json
  def update
    respond_to do |format|
      if @mainpage.update(mainpage_params)
        format.html { redirect_to @mainpage, notice: 'Mainpage was successfully updated.' }
        format.json { render :show, status: :ok, location: @mainpage }
      else
        format.html { render :edit }
        format.json { render json: @mainpage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mainpages/1
  # DELETE /mainpages/1.json
  def destroy
    @mainpage.destroy
    respond_to do |format|
      format.html { redirect_to mainpages_url, notice: 'Mainpage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mainpage
      @mainpage = Mainpage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mainpage_params
      params[:mainpage]
    end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.offset(rand(Quote.count)).first
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
   @quote = Quote.offset(rand(Quote.count)).first
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:quote, :author)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jokes_helper.rb
module JokesHelper
end

app/helpers/mainpages_helper.rb
module MainpagesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/application/_joke.html.erb
<p id="notice"><%= notice %></p>
<table>
  <thead>
    <tr>
      <th>Joke</th>
      <th>Punchline</th>
      <th colspan="3"></th>
    </tr>
  </thead>

 <tbody>
      <tr>
        <td><%= @jokes.joke %></td>
        <td><%= @jokes.punchline %></td>
      </tr>
  </tbody>
</table>
<br>

app/views/application/_quote.html.erb
<p id="notice"><%= notice %></p>
<table>
  <thead>
    <tr>
      <th>Quote</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @quotes.quote %></td>
        <td><%= @quotes.author %></td>
      </tr>
  </tbody>
</table>
<br>

app/views/jokes/_form.html.erb
<%= form_for(@joke) do |f| %>
  <% if @joke.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@joke.errors.count, "error") %> prohibited this joke from being saved:</h2>

      <ul>
      <% @joke.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :joke %><br>
    <%= f.text_field :joke %>
  </div>
  <div class="field">
    <%= f.label :punchline %><br>
    <%= f.text_field :punchline %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jokes/edit.html.erb
<h1>Editing Joke</h1>

<%= render 'form' %>

<%= link_to 'Show', @joke %> |
<%= link_to 'Back', jokes_path %>

app/views/jokes/index.html.erb
<%= @joke.joke + " " + @joke.punchline %></td>
<br>
<%= render 'mainpages/buttonfooter' %>

app/views/jokes/new.html.erb
<h1>New Joke</h1>

<%= render 'form' %>

<%= link_to 'Back', jokes_path %>

app/views/jokes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Joke:</strong>
  <%= @joke.joke %>
</p>

<p>
  <strong>Punchline:</strong>
  <%= @joke.punchline %>
</p>

<%= link_to 'Edit', edit_joke_path(@joke) %> |
<%= link_to 'Back', jokes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HappyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mainpages/_buttonfooter.html.erb
<p>
<button id="jokeButton"> Joke Button</button></a>
<br>
<button id="quoteButton">Quote Button</button></a>
</p>

app/views/mainpages/_form.html.erb
<%= form_for(@mainpage) do |f| %>
  <% if @mainpage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mainpage.errors.count, "error") %> prohibited this mainpage from being saved:</h2>

      <ul>
      <% @mainpage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mainpages/edit.html.erb
<h1>Editing Mainpage</h1>

<%= render 'form' %>

<%= link_to 'Show', @mainpage %> |
<%= link_to 'Back', mainpages_path %>

app/views/mainpages/index.html.erb
<h3>Quotes n' Jokes Ya'll</h3>

<%= render 'buttonfooter' %>

app/views/mainpages/new.html.erb
<h1>New Mainpage</h1>

<%= render 'form' %>

<%= link_to 'Back', mainpages_path %>

app/views/mainpages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_mainpage_path(@mainpage) %> |
<%= link_to 'Back', mainpages_path %>

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quote %><br>
    <%= f.text_field :quote %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<%= @quotes.quote + " " + @quotes.author %>
<br>
<%= render 'mainpages/buttonfooter' %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quote:</strong>
  <%= @quote.quote %>
</p>

<p>
  <strong>Author:</strong>
  <%= @quote.author %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>